package fi.bizhop.finanssi2.db;

import lombok.Value;
import lombok.With;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Value
@Document(collection = "chat")
public class ChatMessage {
    // Generated by MongoDB on save. ObjectIds grow with insertion order, so the id doubles as the paging cursor.
    @Id @With String id;
    String username;
    // Sender's display name at the time of posting; null in messages saved before it was stored
    String name;
    String message;
    long timestamp;
    String photoUrl;
}
