package fi.bizhop.finanssi2.db;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "chat")
public record ChatMessage(
    // Generated by MongoDB on save. ObjectIds grow with insertion order, so the id doubles as the paging cursor.
    @Id String id,
    String username,
    // Sender's display name at the time of posting; null in messages saved before it was stored
    String name,
    String message,
    long timestamp,
    String photoUrl) {

    public ChatMessage withId(String id) {
        return new ChatMessage(id, username, name, message, timestamp, photoUrl);
    }

}
